name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"
          enable-cache: false

      - name: Install Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Analysing the code
        run: |
          uv run mypy trueseeing
          uv run pflake8 --color=never trueseeing
